### ISSUE TITLE
WooCommerce compatibility

### ISSUE THREAD

**Issue by benoitfouc** [tao-software/tao-schedule-update#28] opened 2018-12-17 16:23 UTC
Hello, when i'm trying to schedule a product update, the update is instantly publish and i can see a SKU ( duplicated error).

Can we fix the "instant" publish when we want to schedule a product update in WooCommerce ?

**Comment by Syberspace** [comment] 2019-02-01 15:31
Duplicate of https://wordpress.org/support/topic/product-woocommerce-compatibility/

**Closed as completed by Syberspace** 2019-02-01 15:31 UTC
